// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: controller.proto
#ifndef GRPC_controller_2eproto__INCLUDED
#define GRPC_controller_2eproto__INCLUDED

#include "controller.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace vqro {
namespace rpc {

class VaqueroController GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status LocateSeries(::grpc::ClientContext* context, const ::vqro::rpc::SeriesQuery& request, ::vqro::rpc::LocateSeriesResults* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vqro::rpc::LocateSeriesResults>> AsyncLocateSeries(::grpc::ClientContext* context, const ::vqro::rpc::SeriesQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vqro::rpc::LocateSeriesResults>>(AsyncLocateSeriesRaw(context, request, cq));
    }
    virtual ::grpc::Status ExchangeState(::grpc::ClientContext* context, const ::vqro::rpc::ExchangeStateRequest& request, ::vqro::rpc::ExchangeStateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vqro::rpc::ExchangeStateResponse>> AsyncExchangeState(::grpc::ClientContext* context, const ::vqro::rpc::ExchangeStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vqro::rpc::ExchangeStateResponse>>(AsyncExchangeStateRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vqro::rpc::LocateSeriesResults>* AsyncLocateSeriesRaw(::grpc::ClientContext* context, const ::vqro::rpc::SeriesQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vqro::rpc::ExchangeStateResponse>* AsyncExchangeStateRaw(::grpc::ClientContext* context, const ::vqro::rpc::ExchangeStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status LocateSeries(::grpc::ClientContext* context, const ::vqro::rpc::SeriesQuery& request, ::vqro::rpc::LocateSeriesResults* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vqro::rpc::LocateSeriesResults>> AsyncLocateSeries(::grpc::ClientContext* context, const ::vqro::rpc::SeriesQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vqro::rpc::LocateSeriesResults>>(AsyncLocateSeriesRaw(context, request, cq));
    }
    ::grpc::Status ExchangeState(::grpc::ClientContext* context, const ::vqro::rpc::ExchangeStateRequest& request, ::vqro::rpc::ExchangeStateResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vqro::rpc::ExchangeStateResponse>> AsyncExchangeState(::grpc::ClientContext* context, const ::vqro::rpc::ExchangeStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vqro::rpc::ExchangeStateResponse>>(AsyncExchangeStateRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::vqro::rpc::LocateSeriesResults>* AsyncLocateSeriesRaw(::grpc::ClientContext* context, const ::vqro::rpc::SeriesQuery& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::vqro::rpc::ExchangeStateResponse>* AsyncExchangeStateRaw(::grpc::ClientContext* context, const ::vqro::rpc::ExchangeStateRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_LocateSeries_;
    const ::grpc::RpcMethod rpcmethod_ExchangeState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status LocateSeries(::grpc::ServerContext* context, const ::vqro::rpc::SeriesQuery* request, ::vqro::rpc::LocateSeriesResults* response);
    virtual ::grpc::Status ExchangeState(::grpc::ServerContext* context, const ::vqro::rpc::ExchangeStateRequest* request, ::vqro::rpc::ExchangeStateResponse* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestLocateSeries(::grpc::ServerContext* context, ::vqro::rpc::SeriesQuery* request, ::grpc::ServerAsyncResponseWriter< ::vqro::rpc::LocateSeriesResults>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestExchangeState(::grpc::ServerContext* context, ::vqro::rpc::ExchangeStateRequest* request, ::grpc::ServerAsyncResponseWriter< ::vqro::rpc::ExchangeStateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace rpc
}  // namespace vqro


#endif  // GRPC_controller_2eproto__INCLUDED
