package(default_visibility = ["//visibility:public"])


cc_library(
    name = "controller",
    srcs = [
    ],
    hdrs = [
        "controller.h",
    ],
    deps = [
        "//vqro/base",
        "//vqro/db",
        "//vqro/rpc:vqro_cc_proto",
    ],
)
