package(default_visibility = ["//visibility:public"])

cc_library(
    name = "base",
    srcs = [
        "base.cc",
        "fileutil.cc",
    ],
    hdrs = [
        "base.h",
        "fileutil.h",
        "worker.h"
    ],
)
